apiRevision: edurata.io/v1
name: ticker-forwarder
description: Takes entries from ticker
runtime: python3_10
interface:
  inputs:
    properties:
      OXYLABS_PASSWORD:
        type: env
        title: OXYLABS_PASSWORD
        description: password for oxylabs
  outputs:
    properties:
      posts:
        type: array
        title: posts
        description: posts
        items:
          type: object
          title: post
          description: post
          properties:
            title:
              type: string
              title: title
              description: title
            date:
              type: string
              title: date
              description: date
            ticketUrl:
              type: string
              title: url
              description: url
            content:
              type: string
              title: description
              description: description
            sourceUrl:
              type: string
              title: source
              description: source
