name: ticker-forwarder
description: Takes entries from ticker
runtime: python3_10
interface:
  inputs:
    OXYLABS_PASSWORD:
      type: env
      title: OXYLABS_PASSWORD
      description: password for oxylabs
  outputs:
    properties:
      success:
        type: boolean
        description: Whether the function was successful
